# Generated by Django 3.2.2 on 2021-05-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_picture/%y/%m', verbose_name='post_picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_picture/%y/%m', verbose_name='profile_picture'),
        ),
    ]
